name: CI

on:
  push:
    branches: [main]

  schedule:
    - cron: "15 8 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install git+https://github.com/jooola/pre-commit-hook-sync@v0.1.0

      - run: |
          pre-commit-hook-sync -vv \
            https://x:${GITHUB_TOKEN}@github.com/prettier/prettier \
            --upstream-pattern '*.*.*' \
            --file .npmignore \
            --file .pre-commit-hooks.yaml \
            --file LICENSE \
            --file package.json \
            --file README.md \
            --push
